#!/bin/bash
# SDL helper script sourced by configure

find_sdl() {
  local pkg=sdl
  local config_tool=

  sdl_found="no"
  sdl_cflags=
  sdl_libs=

  if has $pkg_config ; then
    config_tool="$pkg_config $pkg"
    if ! $pkg_config --exists "$pkg" ; then
      if has sdl-config ; then
        config_tool=sdl-config
      else
        return 1
      fi
    fi
  elif has sdl-config ; then
    config_tool=sdl-config
  else
    return 1
  fi

  sdl_found="yes"
  sdl_cflags=$($config_tool --cflags)
  sdl_libs=$($config_tool --libs)

  return 0
}

load_sdl() {
  append_to_config_mak SDL_CFLAGS "$sdl_cflags"
  append_to_config_mak SDL_LIBS   "$sdl_libs"
}

find_sdl && load_sdl

# vim: ts=2 sw=2 sts=0 expandtab
