PLATFORM_DIR=src/platforms/raspberry
PLATFORM_ARCH=arm

CONFIG_RABBITS=y

CONFIG_MEMORY=y
CONFIG_QEMU_WRAPPER=y
CONFIG_RPI_UART=y
CONFIG_RPI_TIMER=y
CONFIG_RPI_SYSTEM_TIMER=y
CONFIG_RPI_MAILBOX=y
CONFIG_RPI_GPIO=y
CONFIG_RPI_IT_CTRL=y
CONFIG_RPI_MINIUART=y
CONFIG_RPI_DMA=y
